from ._exceptions import CommetAPIError, CommetError, CommetValidationError
from ._http import ApiResponse
from ._shared import API_VERSION
from .async_client import AsyncCommet
from .client import Commet
from .resources.webhooks import Webhooks
from .types import (
    Addon,
    ApiKeyCreated,
    ApiKeyData,
    BillingInterval,
    ConsumptionModel,
    CreditPack,
    CreditPackDetail,
    Currency,
    Customer,
    DiscountType,
    Feature,
    FeatureAccess,
    FeatureManage,
    FeatureType,
    InvoiceDetail,
    InvoiceListItem,
    OverageModel,
    Plan,
    PlanGroup,
    PlanGroupDetail,
    PlanManage,
    PlanPriceManage,
    PortalSession,
    PricingMode,
    PromoCode,
    PromoCodeDetail,
    SeatBalance,
    SeatEvent,
    SeatEventType,
    Subscription,
    SubscriptionStatus,
    TransactionDetail,
    TransactionListItem,
    UsageEvent,
    WebhookEndpoint,
    WebhookEndpointCreated,
)

try:
    from importlib.metadata import version

    __version__ = version("commet-sdk")
except Exception:
    __version__ = "0.1.0"

__all__ = [
    "__version__",
    "API_VERSION",
    "Addon",
    "ApiKeyCreated",
    "ApiKeyData",
    "ApiResponse",
    "AsyncCommet",
    "BillingInterval",
    "Commet",
    "CommetAPIError",
    "CommetError",
    "CommetValidationError",
    "ConsumptionModel",
    "CreditPack",
    "CreditPackDetail",
    "Currency",
    "Customer",
    "DiscountType",
    "Feature",
    "FeatureAccess",
    "FeatureManage",
    "FeatureType",
    "InvoiceDetail",
    "InvoiceListItem",
    "OverageModel",
    "Plan",
    "PlanGroup",
    "PlanGroupDetail",
    "PlanManage",
    "PlanPriceManage",
    "PortalSession",
    "PricingMode",
    "PromoCode",
    "PromoCodeDetail",
    "SeatBalance",
    "SeatEvent",
    "SeatEventType",
    "Subscription",
    "SubscriptionStatus",
    "TransactionDetail",
    "TransactionListItem",
    "UsageEvent",
    "WebhookEndpoint",
    "WebhookEndpointCreated",
    "Webhooks",
]
