# AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.
# ruff: noqa: E501

from __future__ import annotations

from typing import Any

from .._http import ApiResponse, CommetHTTPClient
from .._shared import build_body
from ..types import (
    BatchCreateCustomersParamsCustomersItem,
    CreateCustomerParamsAddress,
    Customer,
    CustomerBatch,
    Timezone,
    UpdateCustomerParamsAddress,
    _parse,
    _parse_list,
)


class CustomersResource:
    def __init__(self, http: CommetHTTPClient) -> None:
        self._http = http

    def list(
        self, *, external_id: str | None = None, limit: int | None = None, cursor: str | None = None
    ) -> ApiResponse[list[Customer]]:
        """List customers with cursor-based pagination."""
        query = build_body(external_id=external_id, limit=limit, cursor=cursor)
        return _parse_list(self._http.get("/customers", query), Customer)

    def create(
        self,
        *,
        email: str,
        id: str | None = None,
        external_id: str | None = None,
        full_name: str | None = None,
        address: CreateCustomerParamsAddress | None = None,
        address_id: str | None = None,
        timezone: Timezone | None = None,
        metadata: dict[str, Any] | None = None,
        idempotency_key: str | None = None,
    ) -> ApiResponse[Customer]:
        """Create a new customer. Idempotent when customerId is provided."""
        body = build_body(
            id=id,
            external_id=external_id,
            full_name=full_name,
            address=address,
            address_id=address_id,
            email=email,
            timezone=timezone,
            metadata=metadata,
        )
        return _parse(
            self._http.post("/customers", body, idempotency_key=idempotency_key), Customer
        )

    def get(self, id: str) -> ApiResponse[Customer]:
        """Retrieve a customer by their public ID, including subscription status and metadata."""
        return _parse(self._http.get(f"/customers/{id}"), Customer)

    def update(
        self,
        id: str,
        *,
        email: str | None = None,
        full_name: str | None = None,
        external_id: str | None = None,
        timezone: Timezone | None = None,
        metadata: dict[str, Any] | None = None,
        address: UpdateCustomerParamsAddress | None = None,
        idempotency_key: str | None = None,
    ) -> ApiResponse[Customer]:
        """Update a customer's name, external ID, or metadata."""
        body = build_body(
            email=email,
            full_name=full_name,
            external_id=external_id,
            timezone=timezone,
            metadata=metadata,
            address=address,
        )
        return _parse(
            self._http.put(f"/customers/{id}", body, idempotency_key=idempotency_key), Customer
        )

    def create_batch(
        self,
        *,
        customers: list[BatchCreateCustomersParamsCustomersItem],
        idempotency_key: str | None = None,
    ) -> ApiResponse[CustomerBatch]:
        """Create up to 100 customers in a single request."""
        body = build_body(customers=customers)
        return _parse(
            self._http.post("/customers/batch", body, idempotency_key=idempotency_key),
            CustomerBatch,
        )
