# AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.
# ruff: noqa: E501

from __future__ import annotations

from typing import Any, Literal

from .._http import ApiResponse, CommetHTTPClient
from .._shared import build_body
from ..types import (
    CreatedInvoice,
    Invoice,
    InvoiceDownload,
    InvoiceStatus,
    SentInvoice,
    _parse,
    _parse_list,
)


class InvoicesResource:
    def __init__(self, http: CommetHTTPClient) -> None:
        self._http = http

    def list(
        self,
        *,
        customer_id: str | None = None,
        status: Literal["draft", "outstanding", "paid", "void", "uncollectible"] | None = None,
        subscription_id: str | None = None,
        cursor: str | None = None,
        limit: int | None = None,
    ) -> ApiResponse[list[Invoice]]:
        """List invoices with cursor-based pagination. Filter by customer, status, or subscription."""
        query = build_body(
            customer_id=customer_id,
            status=status,
            subscription_id=subscription_id,
            cursor=cursor,
            limit=limit,
        )
        return _parse_list(self._http.get("/invoices", query), Invoice)

    def get(self, id: str) -> ApiResponse[Invoice]:
        """Retrieve a single invoice by its public ID, including line items."""
        return _parse(self._http.get(f"/invoices/{id}"), Invoice)

    def create_adjustment(
        self,
        *,
        customer_id: str,
        amount: int,
        description: str,
        metadata: dict[str, Any] | None = None,
        idempotency_key: str | None = None,
    ) -> ApiResponse[CreatedInvoice]:
        """Create a one-off adjustment invoice. Use a negative amount for a credit."""
        body = build_body(
            customer_id=customer_id, amount=amount, description=description, metadata=metadata
        )
        return _parse(
            self._http.post("/invoices", body, idempotency_key=idempotency_key), CreatedInvoice
        )

    def get_download_url(self, id: str) -> ApiResponse[InvoiceDownload]:
        """Generate a signed URL to download the invoice as a PDF. The URL expires after 7 days."""
        return _parse(self._http.get(f"/invoices/{id}/download"), InvoiceDownload)

    def send(self, id: str, *, idempotency_key: str | None = None) -> ApiResponse[SentInvoice]:
        """Send the invoice to the customer via email."""
        return _parse(
            self._http.post(f"/invoices/{id}/send", idempotency_key=idempotency_key), SentInvoice
        )

    def update_status(
        self, id: str, *, status: Literal["paid", "void"], idempotency_key: str | None = None
    ) -> ApiResponse[InvoiceStatus]:
        """Mark an outstanding invoice as "paid" or "void". Cannot change the status of already paid or voided invoices."""
        body = build_body(status=status)
        return _parse(
            self._http.put(f"/invoices/{id}/status", body, idempotency_key=idempotency_key),
            InvoiceStatus,
        )
