# AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.
# ruff: noqa: E501

from __future__ import annotations

from .._async_http import AsyncCommetHTTPClient
from .._http import ApiResponse
from .._shared import build_body
from ..types import (
    BulkSeatUpdate,
    SeatBalance,
    SeatBalanceListItem,
    SeatEvent,
    _parse,
    _parse_list,
)


class AsyncSeatsResource:
    def __init__(self, http: AsyncCommetHTTPClient) -> None:
        self._http = http

    async def add(
        self, *, customer_id: str, feature_code: str, count: int, idempotency_key: str | None = None
    ) -> ApiResponse[SeatEvent]:
        """Add seats to a customer's subscription. Prorates charges for the current billing period."""
        body = build_body(customer_id=customer_id, feature_code=feature_code, count=count)
        return _parse(
            await self._http.post("/seats", body, idempotency_key=idempotency_key), SeatEvent
        )

    async def set(
        self, *, customer_id: str, feature_code: str, count: int, idempotency_key: str | None = None
    ) -> ApiResponse[SeatEvent]:
        """Set seats to an exact count."""
        body = build_body(customer_id=customer_id, feature_code=feature_code, count=count)
        return _parse(
            await self._http.put("/seats", body, idempotency_key=idempotency_key), SeatEvent
        )

    async def remove(
        self, *, customer_id: str, feature_code: str, count: int
    ) -> ApiResponse[SeatEvent]:
        """Remove seats from a customer's subscription. Takes effect at the end of the billing period."""
        body = build_body(customer_id=customer_id, feature_code=feature_code, count=count)
        return _parse(await self._http.delete("/seats", body), SeatEvent)

    async def set_all(
        self, *, customer_id: str, seats: dict[str, int], idempotency_key: str | None = None
    ) -> ApiResponse[list[BulkSeatUpdate]]:
        """Set all seat types at once."""
        body = build_body(customer_id=customer_id, seats=seats)
        return _parse_list(
            await self._http.put("/seats/bulk", body, idempotency_key=idempotency_key),
            BulkSeatUpdate,
        )

    async def get_balance(self, *, customer_id: str, feature_code: str) -> ApiResponse[SeatBalance]:
        """Get current balance for a specific seat type."""
        query = build_body(customer_id=customer_id, feature_code=feature_code)
        return _parse(await self._http.get("/seats/balance", query), SeatBalance)

    async def get_all_balances(self, *, customer_id: str) -> ApiResponse[SeatBalanceListItem]:
        """Get the current balance for all seat types in a customer's subscription."""
        query = build_body(customer_id=customer_id)
        return _parse(await self._http.get("/seats/balances", query), SeatBalanceListItem)
